#ifndef __SubCanvasSizeDialog__
#define __SubCanvasSizeDialog__

/**
@file
Subclass of CanvasSizeDialog, which is generated by wxFormBuilder.
*/

#include "OpenPaintGUI.h"

/** Implementing CanvasSizeDialog */
class SubCanvasSizeDialog : public CanvasSizeDialog
{
    private:
        int m_iCurrentWidth;
        int m_iCurrentHeight;

        bool m_bIsLinked;
        double m_dRatio;

        int m_iWidth;
        int m_iHeight;
        int m_iOffsetX;
        int m_iOffsetY;
    protected:
        virtual void OnWidth( wxSpinEvent& event );
        virtual void OnHeight( wxSpinEvent& event );
        virtual void OnLink( wxCommandEvent& event );

        virtual void OnOffsetX( wxSpinEvent& event );
        virtual void OnOffsetY( wxSpinEvent& event );
        virtual void OnCenter( wxCommandEvent& event );
    public:
	    /** Constructor */
	    SubCanvasSizeDialog( wxWindow* parent, int iWidth, int iHeight);
        int GetWidth();
        int GetHeight();
        int GetOffsetX();
        int GetOffsetY();

        void SetWidth(int iWidth);
        void SetHeight(int iHeight);
        void SetOffsetX(int iOffsetX);
        void SetOffsetY(int iOffsetY);
};

#endif // __SubCanvasSizeDialog__

