#ifndef __SubColorPanel__
#define __SubColorPanel__

/**
@file
Subclass of ColorPanel, which is generated by wxFormBuilder.
*/

#include "OpenPaintGUI.h"

/** Implementing ColorPanel */
class SubColorPanel : public ColorPanel
{
protected:
	// Handlers for ColorPanel events.
	void OnForegroundSet( wxColourPickerEvent& event );
	void OnBackgroundSet( wxColourPickerEvent& event );
	
public:
	/** Constructor */
	SubColorPanel( wxWindow* parent );
    void UpdateColors();
};

#endif // __SubColorPanel__
