#ifndef __SubColorPanel__
#define __SubColorPanel__

/**
@file
Subclass of ColorPanel, which is generated by wxFormBuilder.
*/

#include "OpenPaintGUI.h"

/** Implementing ColorPanel */
class SubColorPanel : public ColorPanel
{
public:
	/** Constructor */
	SubColorPanel( wxWindow* parent );
    void UpdateColors();
};

#endif // __SubColorPanel__
