#ifndef __SubImageSizeDialog__
#define __SubImageSizeDialog__

/**
@file
Subclass of ImageSizeDialog, which is generated by wxFormBuilder.
*/

#include "OpenPaintGUI.h"

/** Implementing ImageSizeDialog */
class SubImageSizeDialog : public ImageSizeDialog
{
    private:
        int m_iCurrentWidth;
        int m_iCurrentHeight;

        bool m_bIsLinked;
        double m_dRatio;

        int m_iWidth;
        int m_iHeight;
        int m_iOffsetX;
        int m_iOffsetY;
    protected:
	    // Handlers for ImageSizeDialog events.
	    void OnWidth( wxSpinEvent& event );
	    void OnHeight( wxSpinEvent& event );
	    void OnLink( wxCommandEvent& event );
	
    public:
        /** Constructor */
        SubImageSizeDialog( wxWindow* parent, int iWidth, int iHeight);

        int GetWidth();
        int GetHeight();

        void SetWidth(int iWidth);
        void SetHeight(int iHeight);
};

#endif // __SubImageSizeDialog__

