#ifndef __SubMainFrame__
#define __SubMainFrame__

/**
@file
Subclass of MainFrame, which is generated by wxFormBuilder.
@todo Add your event handlers directly to this file.
*/

#include "OpenPaintGUI.h"

class OpenPaintMDIChildFrame;
class wxAuiNotebook;

/** Implementing MainFrame */
class SubMainFrame : public MainFrame
{
    private:
        DECLARE_EVENT_TABLE()

        enum
        {
            IDX_TAB_MENU_SAVE = 9000,
            IDX_TAB_MENU_SAVE_AS,
            IDX_TAB_MENU_CLOSE,
            IDX_TAB_MENU_CLOSE_OTHERS,
            IDX_TAB_MENU_CLOSE_ALL,
            IDX_TAB_MENU_SPLIT_TOP,
            IDX_TAB_MENU_SPLIT_RIGHT,
            IDX_TAB_MENU_SPLIT_BOTTOM,
            IDX_TAB_MENU_SPLIT_LEFT,
            IDX_TAB_MENU_UNSPLIT_ALL,
            IDX_TAB_MENU_PIN,
            IDX_TAB_MENU_LOCK
        };

    protected:
        virtual void Init();
        virtual void HistoryOpen( wxCommandEvent& event );
        void UpdateHistory();
        void AddFileToHistory(wxString strFilename);
        void OnTabRightUp(wxAuiNotebookEvent& event);
        void OnTabMenu(wxCommandEvent& event);
        wxAuiNotebook* GetTabNotebook() const;
        OpenPaintMDIChildFrame* GetChildFrameAt(size_t pageIndex) const;
        bool ActivateTab(size_t pageIndex);
        bool CloseTab(size_t pageIndex);
        void CloseOtherTabs(size_t pageIndex);
        void CloseAllTabs();
        int GetContextTabIndex() const;

        void OnUndo( wxCommandEvent& event );
		void OnRedo( wxCommandEvent& event );
		void OnCut( wxCommandEvent& event );
		void OnCopy( wxCommandEvent& event );
		void OnPaste( wxCommandEvent& event );
		void OnDelete( wxCommandEvent& event );
		void OnSelectAll( wxCommandEvent& event );
        void OnClear( wxCommandEvent& event );
        void OnFillFGColor( wxCommandEvent& event );
        void OnFillBGColor( wxCommandEvent& event );

        virtual void OnToolWindow( wxCommandEvent& event );
        virtual void OnColorWindow( wxCommandEvent& event );
        virtual void OnToolbar( wxCommandEvent& event );
        virtual void OnStatusBar( wxCommandEvent& event );

        void OnAuiPaneClose( wxAuiManagerEvent& event );
        void OnMenuOpen( wxMenuEvent& event );

        virtual void OnZoomOut( wxCommandEvent& event );
        virtual void OnZoomIn( wxCommandEvent& event );
        virtual void OnNormalZoom( wxCommandEvent& event );
        virtual void OnHistogram( wxCommandEvent& event );
        
        virtual void OnFullscreen( wxCommandEvent& event );

        virtual void OnFlipHorizontal( wxCommandEvent& event );
        virtual void OnFlipVertical( wxCommandEvent& event );
        virtual void OnRotate( wxCommandEvent& event );
        virtual void OnImageSize( wxCommandEvent& event );
        virtual void OnCanvasSize( wxCommandEvent& event );

        virtual void OnPickColor( wxCommandEvent& event );
        virtual void OnPencil( wxCommandEvent& event );
        virtual void OnBrush( wxCommandEvent& event );
        virtual void OnFill( wxCommandEvent& event );
        virtual void OnEraser( wxCommandEvent& event );
        virtual void OnMagnify( wxCommandEvent& event );
        virtual void OnSprayCan( wxCommandEvent& event );
        virtual void OnLine( wxCommandEvent& event );
        virtual void OnCurve( wxCommandEvent& event );
        virtual void OnRectangle( wxCommandEvent& event );
        virtual void OnEllipse( wxCommandEvent& event );
        virtual void OnRectangleRounded( wxCommandEvent& event );
        virtual void OnPolygon( wxCommandEvent& event );
        virtual void OnSelect( wxCommandEvent& event );
        virtual void OnSelectLasso( wxCommandEvent& event );
        virtual void OnText( wxCommandEvent& event );

        virtual void OnInvertColors( wxCommandEvent& event );
        virtual void OnBlur( wxCommandEvent& event );
        virtual void OnPixelize( wxCommandEvent& event );
        virtual void OnGreyscale( wxCommandEvent& event );
        virtual void OnMonochrome( wxCommandEvent& event );
        

        virtual void OnFont( wxCommandEvent& event );
        virtual void OnForeground( wxCommandEvent& event );
        virtual void OnBackground( wxCommandEvent& event );

        virtual void OnNewFile320( wxCommandEvent& event );
        virtual void OnNewFile640( wxCommandEvent& event );
        virtual void OnNewFile( wxCommandEvent& event );
        virtual void OnNewFile1024( wxCommandEvent& event );

        virtual void OnOpenFile( wxCommandEvent& event );
        virtual void OnSave( wxCommandEvent& event );
        virtual void OnSaveAs( wxCommandEvent& event );
        virtual void OnClose( wxCloseEvent& event );
        virtual void OnExit( wxCommandEvent& event );
        virtual void OnAbout( wxCommandEvent& event );

        virtual void OnSize(wxSizeEvent& event);
        virtual void SetMenuBar(wxMenuBar* menuBar);
        virtual void Shutdown();

        wxMenu *m_menuRecentImages;

        wxAuiManager * m_mAuiManager;
        bool m_ownsAuiManager;
        int m_contextTabIndex;

    public:
	    /** Constructor */
	    SubMainFrame( wxWindow* parent, int id = wxID_ANY, wxString title = wxT("OpenPaint"), wxPoint pos = wxDefaultPosition, wxSize size = wxSize( 1024,768 ), int style = wxDEFAULT_FRAME_STYLE|wxTAB_TRAVERSAL );
        virtual ~SubMainFrame();

        void NewFile(int width = 800, int height = 600);
        void OpenFile(wxString strFilename);
        bool SaveFile();
        void OpenLastFiles();
        bool SaveAs();
};

#endif // __SubMainFrame__

