#ifndef __SubToolPanel__
#define __SubToolPanel__

/**
@file
Subclass of ToolPanel, which is generated by wxFormBuilder.
*/

#include "OpenPaintGUI.h"

/** Implementing ToolPanel */
class SubToolPanel : public ToolPanel
{
protected:
    virtual void EnableTools();
    // Removes and destroys any tool-properties panel currently shown
    // inside m_sbSizerToolProperties (e.g. the BrushToolPanel). Safe to
    // call when the sizer is empty.
    void ClearToolProperties();
    // Re-layouts this panel and asks the owning wxAuiManager to re-fit
    // the pane so size changes are applied immediately (without this the
    // new controls only appear after toggling View > Tool Window).
    void UpdateToolPropertiesLayout();
    // Inserts a wxFormBuilder-generated properties panel into the
    // tool-properties sizer (showing it first, since those panels
    // construct themselves hidden by default).
    void AddToolPropertiesPanel(wxWindow* panel);
	// Handlers for ToolPanel events.

public:
	/** Constructor */
	SubToolPanel( wxWindow* parent );
	void OnPickColor( wxCommandEvent& event );
    void OnPencil( wxCommandEvent& event );
    void OnBrush( wxCommandEvent& event );
	void OnFill( wxCommandEvent& event );
	void OnEraser( wxCommandEvent& event );
	void OnMagnify( wxCommandEvent& event );
	void OnSprayCan( wxCommandEvent& event );
    void OnLine( wxCommandEvent& event );
    void OnCurve( wxCommandEvent& event );
	void OnRectangle( wxCommandEvent& event );
    void OnEllipse( wxCommandEvent& event );
    void OnRectangleRounded( wxCommandEvent& event );
    void OnPolyline( wxCommandEvent& event );
    void OnPolygon( wxCommandEvent& event );
	void OnSelect( wxCommandEvent& event );
    void OnSelectLasso( wxCommandEvent& event );
	void OnText( wxCommandEvent& event );
};

#endif // __SubToolPanel__
